imports:
  - { resource: vendor/henrivantsant/swift/src/services.yaml }

parameters:
  # ...

services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: true

  MyApp\:
    resource: 'app/MyApp/*'