enable_firewalls: true
firewalls:
    main: { login_throttling: { max_attempts: 5 }, token: { validity: 24 } }
role_hierarchy:
    ROLE_GUEST: {  }
    ROLE_USER: [ROLE_TESTING, ROLE_TESTING2]
    ROLE_CLIENT: [ROLE_USERS_LIST]
    ROLE_ADMIN: [ROLE_USERS_LIST, ROLE_SUPER_ADMIN]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
access_decision_manager:
    strategy: Swift\Security\Authorization\Strategy\AffirmativeDecisionStrategy
    allow_if_all_abstain: false
access_control:
    - { path: ^/foo, ip: [84.31.60.101, 84.31.60.193], roles: [IS_AUTHENTICATED] }
graphql_access_control: {  }
rate_limit:
    enabled: true
    enable_default: true
    default_limit: 30
    default_period: 60
    default_strategy: sliding_window
    rates:
        - { name: foo_bar, strategy: sliding_window, limit: 20, period: 60 }